this.$storeでエラーになる問題対応
error TS2339: Property '$store' does not exist on type 'CreateComponentPublicInstance<{}, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, {}, {}, false, OptionTypesType<{}, {}, {}, {}, {}, {}>, ... 5 more ..., {}>'.

https://vuex.vuejs.org/guide/typescript-support.html#typing-store-property-in-vue-component